---
name: Checkmarx One

"on":
  push:
    branches:
      - "**"
  schedule:
    # M-F at 2 am UTC
    - cron: '0 2 * * 1-5'
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  checkmarx:
    # 1.0.8
    uses: cognizant-ai-lab/build-common/.github/workflows/_checkmarx.yml@30321843331e00848309b34e08b839e1f6490ba2
    with:
      base-uri: ${{ vars.CX_BASE_URI }}
      cx-tenant: ${{ vars.CX_TENANT }}
      cx-client-id: ${{ vars.CX_CLIENT_ID }}
      scan-params: '--sast-preset-name "Checkmarx Default"'
    secrets:
      CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
